# Generated by Django 5.2 on 2025-05-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_url_short_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={},
        ),
        migrations.RenameField(
            model_name='url',
            old_name='orginal_url',
            new_name='original_url',
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
